### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format.

server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:bootexample;MODE=MySQL
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
  file:
    name: boot_example.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: spring-boot-rest-example
    version: 0.5.1
    description: Example REST API using Spring Boot

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop